version: 2
sources:
  - name: SNOWFLAKE_SAMPLE_DATA
    database: SNOWFLAKE_SAMPLE_DATA
    schema: tpch_sf100
    tables: 
      - name: orders
      - name: region
      - name: nation
      - name: customer
      - name: lineitem