version: 2

models:
  - name: stg_customer
    description: This model conatins the staging tables 
    columns:
      - name: customerkey
        tests:
          - unique
          - not_null

  - name: stg_orders
    columns:
      - name: orderkey
        tests:
          - unique
          - not_null
      - name: order_status
        tests:
          - accepted_values:
              values: ['P', 'F', 'O']
      - name: customerkey
        tests:
          - not_null
          - relationships:
              to: ref('stg_customers')
              field: customerkey
  - name: stg_nation
    columns:
      - name: nationkey
        tests:
          - unique
          - not_null
  - name: stg_orderitem
    columns:
      - name: orderkey
        tests:
          - not_null
  - name: stg_region
    columns:
      - name: regionkey
        tests:
          - unique
          - not_null